version: 2

updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Vienna
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Europe/Vienna
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Vienna
    open-pull-requests-limit: 5
    groups:
      dockerfile-images:
        patterns:
          - "*"

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:45"
      timezone: Europe/Vienna
    open-pull-requests-limit: 5
    groups:
      production-container-images:
        patterns:
          - "*"

  - package-ecosystem: docker-compose
    directory: /demo
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Vienna
    open-pull-requests-limit: 5
    groups:
      demo-container-images:
        patterns:
          - "*"
