services:
  caddy:
    image: caddy:2-alpine@sha256:6aeddd44c3078b0f9a35206472a11420648a79c184603ef95957d0a20044cb2b
    ports:
      - "8080:80"
    volumes:
      - site-data:/site:ro
      - ../Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      ZEITFENSTER_ALLOWED_EMBED_ORIGINS: "${ZEITFENSTER_ALLOWED_EMBED_ORIGINS:-'none'}"
    depends_on:
      - app
    networks:
      - frontend

  app:
    build: ..
    volumes:
      - site-data:/site
      - ./config.yaml:/etc/zeitfenster/config.yaml:ro
    env_file:
      - ./.env
    depends_on:
      init-calendars:
        condition: service_completed_successfully
      mailpit:
        condition: service_started
    networks:
      - frontend
      - backend
    expose:
      - "8000"

  radicale:
    image: tomsquest/docker-radicale:latest@sha256:419e0c005b63bd475d50f73c5e7ff2b1f04924edb94af525fa86faed213c632a
    volumes:
      - ./radicale/config:/config/config:ro
      - ./radicale/users:/config/users:ro
      - radicale-data:/data
    networks:
      - backend
    expose:
      - "5232"

  init-calendars:
    image: curlimages/curl:latest@sha256:58adaa4e8dca9c988bae2aba4ab3434a0bb2da16bbe3f92dec39ec7785166777
    volumes:
      - ./init-calendars.sh:/init-calendars.sh:ro
    entrypoint: ["/bin/sh", "/init-calendars.sh"]
    depends_on:
      - radicale
    networks:
      - backend

  mailpit:
    image: axllent/mailpit:latest@sha256:ed9b00c609e77e99c79b93f1178255ebc271868920f2c69a8d166bd5634ed10d
    ports:
      - "8025:8025"
    networks:
      - frontend
      - backend
    expose:
      - "1025"

volumes:
  site-data:
  radicale-data:

networks:
  frontend:
  backend:
    internal: true
